spring.application.name=charts

spring.datasource.url=jdbc:postgresql://psql01.mikr.us:5432/db_jola238
spring.datasource.username=jola238
spring.datasource.password=A0ED_6d78c0

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
hibernate.jdbc.lob.non_contextual_creation=true
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.open-in-view=false

server.port=${PORT:8080}